- hosts: all
  remote_user: root
  gather_facts: yes
  any_errors_fatal: true
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: charlie
      state: present
      key: "{{ lookup('file', './hosts.a') }}"
