- hosts: all
  remote_user: root
  gather_facts: yes
  any_errors_fatal: true
  tasks:
    - name: Set up multiple authorized keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - authorized_keys
    - name: Set up multiple authorized keys
      ansible.posix.authorized_key:
        user: mooadmin
        state: present
        key: '{{ item }}'
      with_file:
        - authorized_keys
